### PR TITLE
BioFormats 6.5.0

### PR DESCRIPTION
**Pull request by 0x00b1**

### CODE REVIEW

**Comment by sbesson** [comment]
@0x00b1 looking at the errors reported by Travis (`JavaException: Invalid T index: 1/1` while reading TIFF files), I suspect the failures are related to the issue raised as https://github.com/ome/bioformats/issues/3571.

Short-term, I expect https://github.com/ome/bioformats/pull/3576 will help selecting a more appropriate reader for multi-page TIFF files in the `bioformats.ImageReader` API. Let us know if you would like some JARs allowing to test these changes in the context of `python-bioformats`. We will keep you posted when a formal release of Bio-Formats including this fix is out.

**Comment by petrovm3** [comment]
I am testing this new release candidate and I identified an issue (potentially related to the loci jar version).

I tried to load a Leica scn image excuting the following python code:

> import javabridge
> import bioformats
> from bioformats import log4j
> import sys
> import pylab    
> import os
> 
> javabridge.start_vm(class_path=bioformats.JARS,
>                     run_headless=True)
> 					
> 					try:
>     full_image_path = '/pstore/data/ps-pathology/TiMAP/roche-qc/input_WSI/WSI.formats/0001_Versa8.scn'
>     
>     image, scale = bioformats.load_image(full_image_path, rescale=False, wants_max_intensity=True)
> 
>     try:
>         pylab.imshow(image)
>         pylab.gca().set_title(image_path)
>         pylab.show()
>     except:
>         print(image.shape)
> finally:
>     javabridge.kill_vm() 

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Failed to get class loci/common/RandomAccessInputStream
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
<ipython-input-3-517934f8d5c1> in <module>
      2     full_image_path = '/pstore/data/ps-pathology/TiMAP/roche-qc/input_WSI/WSI.formats/0001_Versa8.scn'
      3 
----> 4     image, scale = bioformats.load_image(full_image_path, rescale=False, wants_max_intensity=True)
      5 
      6     try:

~/.local/lib/python3.7/site-packages/python_bioformats-1.5.3.dev14+g7492cc0-py3.7.egg/bioformats/formatreader.py in load_using_bioformats(path, c, z, t, series, index, rescale, wants_max_intensity, channel_names)
   1002     '''
   1003 
-> 1004     with ImageReader(path=path) as rdr:
   1005         return rdr.read(c, z, t, series, index, rescale, wants_max_intensity,
   1006                         channel_names)

~/.local/lib/python3.7/site-packages/python_bioformats-1.5.3.dev14+g7492cc0-py3.7.egg/bioformats/formatreader.py in __init__(self, path, url, perform_init)
    624         self.stream = jutil.make_instance('loci/common/RandomAccessInputStream',
    625                                           '(Ljava/lang/String;)V',
--> 626                                           self.path)
    627 
    628         self.rdr = None

~/.local/lib/python3.7/site-packages/python_javabridge-4.0.0rc1-py3.7-linux-x86_64.egg/javabridge/jutil.py in make_instance(class_name, sig, *args)
   1713     jexception = get_env().exception_occurred()
   1714     if jexception is not None:
-> 1715         raise JavaException(jexception)
   1716     method_id = get_env().get_method_id(klass, '<init>', sig)
   1717     jexception = get_env().exception_occurred()

JavaException: loci/common/RandomAccessInputStream : Unsupported major.minor version 52.0

**Comment by petrovm3** [comment]
Hello,

When testing this new candidate release (Bioformat 6.5.0), I discovered an issue when reading Ventana BIF files:

**AttributeError: 'JavaException' object has no attribute 'message'**

The source code for my test is:

```
import javabridge
import bioformats
from bioformats import log4j
import sys
import pylab    
import os

javabridge.start_vm(class_path=bioformats.JARS,
                    run_headless=True)

try:
    full_image_path = './animal 403.bif'
    
    image, scale = bioformats.load_image(full_image_path, rescale=False, wants_max_intensity=True)

    try:
        pylab.imshow(image)
        pylab.gca().set_title(image_path)
        pylab.show()
    except:
        print(image.shape)
finally:
    javabridge.kill_vm() 

```
Enclosed the error call stack:

```
---------------------------------------------------------------------------
JavaException                             Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/python_bioformats-1.5.3.dev14+g7492cc0-py3.7.egg/bioformats/formatreader.py in init_reader(self)
    732         try:
--> 733             self.rdr.setId(self.path)
    734         except jutil.JavaException as e:

~/.local/lib/python3.7/site-packages/python_bioformats-1.5.3.dev14+g7492cc0-py3.7.egg/bioformats/formatreader.py in setId(self, path)
    205                        '(Ljava/lang/String;)V',
--> 206                        path)
    207 

~/.local/lib/python3.7/site-packages/python_javabridge-4.0.0rc1-py3.7-linux-x86_64.egg/javabridge/jutil.py in call(o, method_name, sig, *args)
    886     nice_args = get_nice_args(args, args_sig)
--> 887     result = fn(*nice_args)
    888     x = env.exception_occurred()

~/.local/lib/python3.7/site-packages/python_javabridge-4.0.0rc1-py3.7-linux-x86_64.egg/javabridge/jutil.py in fn(*args)
    853             if x is not None:
--> 854                 raise JavaException(x)
    855             return result

JavaException: No IFDs found

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-3-bc9b067969e1> in <module>
     12     full_image_path = './animal 403.bif'
     13 
---> 14     image, scale = bioformats.load_image(full_image_path, rescale=False, wants_max_intensity=True)
     15 
     16     try:

~/.local/lib/python3.7/site-packages/python_bioformats-1.5.3.dev14+g7492cc0-py3.7.egg/bioformats/formatreader.py in load_using_bioformats(path, c, z, t, series, index, rescale, wants_max_intensity, channel_names)
   1002     '''
   1003 
-> 1004     with ImageReader(path=path) as rdr:
   1005         return rdr.read(c, z, t, series, index, rescale, wants_max_intensity,
   1006                         channel_names)

~/.local/lib/python3.7/site-packages/python_bioformats-1.5.3.dev14+g7492cc0-py3.7.egg/bioformats/formatreader.py in __init__(self, path, url, perform_init)
    672         self.rdr.o = jrdr
    673         if perform_init:
--> 674             self.init_reader()
    675 
    676     def download(self, url):

~/.local/lib/python3.7/site-packages/python_bioformats-1.5.3.dev14+g7492cc0-py3.7.egg/bioformats/formatreader.py in init_reader(self)
    733             self.rdr.setId(self.path)
    734         except jutil.JavaException as e:
--> 735             logger.warn(e.message)
    736             for line in traceback.format_exc().split("\n"):
    737                 logger.warn(line)

AttributeError: 'JavaException' object has no attribute 'message'
```

**Comment by 0x00b1** [comment]
@petrovm3 Would you mind pasting the output of `pip freeze`?

**Comment by petrovm3** [comment]
Enclosed the outcome of pip freeze

[pip_freeze.txt](https://github.com/CellProfiler/python-bioformats/files/4843930/pip_freeze.txt)

**Comment by petrovm3** [comment]
@0x00b1 : tiles iteration isn't iterating as expected

Based on the [Bioformats Java code](https://docs.openmicroscopy.org/bio-formats/6.5.0/developers/tiling.html?highlight=tile%20image) for tiles iteration, I translated the corresponding code in Python and I noticed during the iteration that openBytes() always returns the same array. Is there a bug or is something missing in my code ? Attached full full code

Thanks for your feedback.

[bio-formats-reading-tiles.txt](https://github.com/CellProfiler/python-bioformats/files/4844170/bio-formats-reading-tiles.txt)

for y in range(nYTiles):
    for x in range(nXTiles):
        # The x and y coordinates for the current tile
        tileX = x * tileSizeX
        tileY = y * tileSizeY

        # Read tiles from the input file and write them to the output OME-Tiff
        buf = reader.openBytes(0, tileX, tileY, tileSizeX, tileSizeY)
        print('tileX = {}; tileY = {}; Image Index = {}; Buffer shape = {}; buf = {};'.format(tileX, tileY, buf.shape[0], buf))


tileX = 0; tileY = 0; Image Index = 0; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 256; tileY = 0; Image Index = 1; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 512; tileY = 0; Image Index = 2; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 768; tileY = 0; Image Index = 3; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 1024; tileY = 0; Image Index = 4; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 1280; tileY = 0; Image Index = 5; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 1536; tileY = 0; Image Index = 6; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 1792; tileY = 0; Image Index = 7; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 2048; tileY = 0; Image Index = 8; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 2304; tileY = 0; Image Index = 9; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];
tileX = 2560; tileY = 0; Image Index = 10; Buffer shape = 497664000; buf = [242 242 242 ... 237 237 237];

**Comment by petrovm3** [comment]
> @petrovm3 Would you mind pasting the output of `pip freeze`?

@0x00b1 : I found the issue. In fact it isn't specific to the file format. The name of the file contains white spaces and this makes the problem. I renamed the spaces with underscore and the issue disappeared. Please forget this issue. I will inform our technicians to not use special characters like white space and %

**Comment by sbesson** [comment]
Note with Bio-Formats 6.5.1 being released, the unit tests should now pass - see also #131 which is bumping the JAR to the latest version.

**Pull request closed without merging**
