### PR TITLE
Shim to pip install in python2+3 (#56)

### PR DESCRIPTION
**Pull request by jnj16180340**
Python-bioformats now installs in python3.5 and python2.7 (see #56). 

A more permanent solution might involve doing str/bytes conversion in `get_version()`

### CODE REVIEW

**Comment by jnj16180340** [comment]
Does this indicate a problem with the build server or something else
````
conda-build               1.16.0                   py27_0    defaults
install.11
0.00s$ cd $TRAVIS_REPO_SLUG
0.33s$ conda create --use-local -n testenv python=$PYTHON_VERSION
Fetching package metadata ...CondaHTTPError: HTTP Error: Could not find URL: file:///home/travis/miniconda/conda-bld/linux-64/
The command "conda create --use-local -n testenv python=$PYTHON_VERSION" failed and exited with 1 during .
Your build has been stopped.
````

**Comment by mcquin** [comment]
@jnj16180340 I'm currently working on fixing the Travis build.

**Comment by mcquin** [comment]
@jnj16180340 OK Travis is happy again. You'll need to rebase you changes on latest master.

**Comment by jnj16180340** [comment]
Hardcoding the version in 1.0.9 is a better fix, though

**Pull request closed without merging**
