### PR TITLE
Fix bug that prevented setting values for "AcquiredDate" attribute

### PR DESCRIPTION
**Pull request by HackerMD**
Also change name of the attribute from "AcquiredDate" to
"AcquisitionDate" according to the OME model

### CODE REVIEW

**Comment by HackerMD** [comment]
relates to issue #38

**Comment by LeeKamentsky** [comment]
Hi @HackerMD - I pushed your branch to our repo and committed 0810d75bda9a3ef0f318733a3510d8b28ddf759d (and then merged with master so it would build on Travis). Could you review and cherry pick? Thanks for submitting the request.

**Comment by LeeKamentsky** [comment]
@HackerMD also 5e0fd6e needs to be merged in.

**Comment by HackerMD** [comment]
I fetched the upstream "acquistion_date" branch, merged it and ran `nosetests.py`. Looks fine:

```
...........(640, 640)
.........................................................................................................................
----------------------------------------------------------------------
Ran 132 tests in 24.162s

OK
```

**Comment by HackerMD** [comment]
Thanks for immediately taking care of it!

**Comment by LeeKamentsky** [comment]
Can you add my two commits to the pull request? I'll merge after that.

**Comment by LeeKamentsky** [comment]
Excellent - thanks. LMK if you have any more additions or questions (although I'm out next week).

**Pull request merged**
