### PR TITLE
Attempt to add Travis CI support

### PR DESCRIPTION
**Pull request by jakirkham**
How this works.

* Try to handle Python and related dependencies with [`conda`]( http://conda.pydata.org/docs/ ). Makes it really easy to install `numpy` and the sort. Also, uses binaries so it is really fast (no build time). Usually, has recent versions.
* Uses a Java language environment. It is needed for some things in here anyways. Also, the Travis Python environment would be replaced with `conda`'s so we don't care about it.
* Use `pip` to install the latest `python-javabridge`. Easy to do. Likely what someone will do when installing themselves.
* Builds the `sphinx` docs with the `html` target. Just verifies the `docs` can still be built. May provide elucidating warnings in-case somebody isn't following correct syntax.
* Provides some coverage setting. Could be used to report to [coveralls.io]( https://coveralls.io/ ) given some tweaks to `python-javabridge`.

### CODE REVIEW

**Comment by LeeKamentsky** [comment]
:+1: looking forward to it, thx.

**Comment by jakirkham** [comment]
If you setup [`coveralls`]( https://coveralls.io/ ) now, I can enable support for it in this PR. I can some default settings for it, but you may wish to fine tune it further.

**Comment by jakirkham** [comment]
Alright, this works. I'm rolling back the coverage support during testing as it will require a change to `python-javabridge` to support it. I left the original commit in there so if you want to take a look at how it would of worked you can.

**Comment by jakirkham** [comment]
Alright, this works. I'm rolling back the coverage support during testing as it will require a change to `python-javabridge` to support it. I left the original commit in there so if you want to take a look at how it would of worked you can.

**Comment by LeeKamentsky** [comment]
Nice. @0x00B1 what do you think? It runs the unit tests - I like. IMHO - getting the travis build status is the big win we wanted. Code coverage would be nice, but we wouldn't act on the results for a while at least.

**Comment by jakirkham** [comment]
There could be a way to workaround this using `coverage run` ( http://coverage.readthedocs.org/en/latest/#quick-start ). Though `nose` already supports coverage with a simple option. Its just a matter of getting `python-javabridge` to allow for that option. So, it shouldn't be hard, but I didn't want to hang this up over getting those set up and in sync.

**Comment by jakirkham** [comment]
Also, it might be worth build the docs, but I'm not quite sure how you do that for your project. I tried running `make html` inside the `docs` directory, but got several tracebacks regarding a failure to import `javabridge`, which was installed in the environment. So, it may take some more playing around.

**Comment by jakirkham** [comment]
Added a doc building step, as well.

**Comment by jakirkham** [comment]
Tried to better lay out my rational for my design choices above.

**Pull request merged**
