### PR TITLE
swap from log4j to logback

### LINKED ISSUE #153: Remove outdated references to log4j
Per investigation in #152 and https://github.com/ome/bioformats/issues/3755 , to our best knowledge we do NOT in the 4.X release versions have log4j in our packages, but we still have some comments and code related to it. Best to dig those out.

### PR DESCRIPTION
**Pull request by bethac07**
Resolves #153

All tests passing locally, and can still open bioformats-requiring files in local cellprofiler.

### CODE REVIEW

**Comment by bethac07** [comment]
Some tests in `core` now failing, digging in

**Comment by bethac07** [comment]
They... stopped failing and I don't know why?

All tests now passing in core and CellProfiler

**Review by DavidStirling — APPROVED** [review]
LGTM, all tests passing on my end

**Comment by gnodar01** [comment]
Should `loci_tools.jar` also be replaced in [setup.cfg](https://github.com/CellProfiler/python-bioformats/blob/c03fb0988caf686251707adc4332d0aff9f02941/setup.cfg#L3)?

**Pull request merged**
